require "spec"
require 'lib/fixnum.rb'

describe Fixnum do

  it "should give me a list of number that compose it by position" do
    2456.decompose.should == [6, 50, 400, 2000]
    3.decompose.should == [3]
  end

  it "should give the roman version of it" do
    0.to_roman.should == ""
    1.to_roman.should == "I"
    2.to_roman.should == "II"
    3.to_roman.should == "III"
    4.to_roman.should == "IV"
    5.to_roman.should == "V"
    6.to_roman.should == "VI"
    7.to_roman.should == "VII"
    8.to_roman.should == "VIII"
    9.to_roman.should == "IX"
    10.to_roman.should == "X"
    11.to_roman.should == "XI"
    12.to_roman.should == "XII"
    13.to_roman.should == "XIII"
    14.to_roman.should == "XIV"
    15.to_roman.should == "XV"
    16.to_roman.should == "XVI"
    17.to_roman.should == "XVII"
    18.to_roman.should == "XVIII"
    19.to_roman.should == "XIX"
    20.to_roman.should == "XX"
    21.to_roman.should == "XXI"
    25.to_roman.should == "XXV"
    30.to_roman.should == "XXX"
    35.to_roman.should == "XXXV"
    40.to_roman.should == "XL"
    45.to_roman.should == "XLV"
    49.to_roman.should == "XLIX"
    50.to_roman.should == "L"
    60.to_roman.should == "LX"
    69.to_roman.should == "LXIX"
    70.to_roman.should == "LXX"
    76.to_roman.should == "LXXVI"
    80.to_roman.should == "LXXX"
    90.to_roman.should == "XC"
    99.to_roman.should == "XCIX"
    100.to_roman.should == "C"
    150.to_roman.should == "CL"
    200.to_roman.should == "CC"
    300.to_roman.should == "CCC"
    400.to_roman.should == "CD"
    500.to_roman.should == "D"
    600.to_roman.should == "DC"
    666.to_roman.should == "DCLXVI"
    700.to_roman.should == "DCC"
    800.to_roman.should == "DCCC"
    900.to_roman.should == "CM"
    1000.to_roman.should == "M"
    1444.to_roman.should == "MCDXLIV"
    1666.to_roman.should == "MDCLXVI"
    1888.to_roman.should == "MDCCCLXXXVIII"
    1990.to_roman.should == "MCMXC"
    1997.to_roman.should == "MCMXCVII"
    1999.to_roman.should == "MCMXCIX"
    2000.to_roman.should == "MM"
    2001.to_roman.should == "MMI"
    2009.to_roman.should == "MMIX"
    2500.to_roman.should == "MMD"
    3000.to_roman.should == "MMM"
    4000.to_roman.should == "M(V)"
    5000.to_roman.should == "(V)"
    6666.to_roman.should == "(V)MDCLXVI"
    10000.to_roman.should == "(X)"
    50000.to_roman.should == "(L)"
    100000.to_roman.should == "(C)"
    500000.to_roman.should == "(D)"
    1000000.to_roman.should == "(M)"
  end

end